
export enum StatusEnum {
  ACTIVE = "ACTIVE",
  SUSPENDED ="SUSPENDED",
  EXPIRED ="EXPIRED",
  CANCELLED="EXPIRED",
  HOLD =  "HOLD",
  APPROVED="APPROVED",
  CLOSED ="CLOSED",
  NEW = "NEW",
  FAILED = "FAILED",
  COMPLETED = "COMPLETED",
  REFUND = "EXPIRED",
}
